# version: "3"
# services:
#   client:
#     container_name: magmer-client
#     restart: unless-stopped
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./client
#     command: npm run start
#     ports:
#       - "3000:3000"
#     stdin_open: true
#     tty: true
#     volumes:
#       - ./client/src:/app/src
#       - ./client/public:/app/public

#   dashboard:
#     container_name: magmer-dashboard
#     restart: unless-stopped
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./dashboard
#     command: npm run start
#     ports:
#       - "3001:3001"
#     stdin_open: true
#     tty: true
#     volumes:
#       - ./dashboard/src:/app/src
#       - ./dashboard/public:/app/public
